// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sentinel.proto

package server

import (
	"context"

	"SentinelGrain/rpc/internal/logic"
	"SentinelGrain/rpc/internal/svc"
	"SentinelGrain/rpc/pb"
)

type SentinelServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSentinelServer
}

func NewSentinelServer(svcCtx *svc.ServiceContext) *SentinelServer {
	return &SentinelServer{
		svcCtx: svcCtx,
	}
}

func (s *SentinelServer) Check(ctx context.Context, in *pb.CheckRequest) (*pb.CheckResponse, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
