// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ListQuotaReq struct {
	AppId    string `form:"appId,optional"`    // 可选过滤
	Resource string `form:"resource,optional"` // 可选过滤
	Page     int64  `form:"page,default=1"`
	Size     int64  `form:"size,default=20"`
}

type ListQuotaResp struct {
	Total int64       `json:"total"`
	Rules []QuotaRule `json:"rules"`
}

type QuotaRule struct {
	AppId      string `json:"appId"`      // 应用标识
	Resource   string `json:"resource"`   // API Path 或 Service Name
	Threshold  int64  `json:"threshold"`  // 阈值
	Period     int64  `json:"period"`     // 窗口期(秒)
	UpdateTime int64  `json:"updateTime"` // 更新时间
}

type SaveQuotaReq struct {
	Rule QuotaRule `json:"rule"`
}

type SaveQuotaResp struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}
