// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	quota "SentinelGrain/api/internal/handler/quota"
	"SentinelGrain/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 保存配额规则
				Method:  http.MethodPost,
				Path:    "/quota",
				Handler: quota.SaveQuotaHandler(serverCtx),
			},
			{
				// 查询配额规则列表
				Method:  http.MethodGet,
				Path:    "/quota",
				Handler: quota.ListQuotaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
